// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_eUZjJy7Fdjj10Lha1ytwc6qhGDa6d0Q',
    appId: '1:865951382682:web:fb947f057908c8d153f323',
    messagingSenderId: '865951382682',
    projectId: 'barber-bloc',
    authDomain: 'barber-bloc.firebaseapp.com',
    storageBucket: 'barber-bloc.appspot.com',
    measurementId: 'G-VVT5CDJRPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASiC4UgFWv5JPGJIDLx46fBFElyHeInNY',
    appId: '1:865951382682:android:b1c3fa62fef4b49553f323',
    messagingSenderId: '865951382682',
    projectId: 'barber-bloc',
    storageBucket: 'barber-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg89rt9AJWP1TSN1n--KDewV1VGRB-wlA',
    appId: '1:865951382682:ios:b3780bfc1916d3ae53f323',
    messagingSenderId: '865951382682',
    projectId: 'barber-bloc',
    storageBucket: 'barber-bloc.appspot.com',
    iosBundleId: 'com.example.barberBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg89rt9AJWP1TSN1n--KDewV1VGRB-wlA',
    appId: '1:865951382682:ios:b3780bfc1916d3ae53f323',
    messagingSenderId: '865951382682',
    projectId: 'barber-bloc',
    storageBucket: 'barber-bloc.appspot.com',
    iosBundleId: 'com.example.barberBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_eUZjJy7Fdjj10Lha1ytwc6qhGDa6d0Q',
    appId: '1:865951382682:web:0d58e71e69ea4c7953f323',
    messagingSenderId: '865951382682',
    projectId: 'barber-bloc',
    authDomain: 'barber-bloc.firebaseapp.com',
    storageBucket: 'barber-bloc.appspot.com',
    measurementId: 'G-GP01KKP3EB',
  );
}
